GET http://localhost:3000/blogs
###
GET http://localhost:3000/blogs/7/0
###
PUT http://localhost:3000/blogs/revise/24
Content-Type: application/json

{
    "post": "$0 Sometimes I think the expectations of productivity thrust upon us is a way to keep us trapped $1",
    "media": "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/IF5ZXZWQWUI6RA6WFEP45LJKWE.jpg&w=1200,https://www.somethingwagging.com/wp-content/uploads/2013/08/medium_102798909.jpg",
    "user_id": 7
}

###
POST http://localhost:3000/blogs
Content-Type: application/json

{
    "post": "$0 Sometimes I think the expectations of productivity thrust upon us is a way to keep us trapped $1",
    "media": "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/IF5ZXZWQWUI6RA6WFEP45LJKWE.jpg&w=1200,https://www.somethingwagging.com/wp-content/uploads/2013/08/medium_102798909.jpg",
    "user_id": 7
}

###

DELETE http://localhost:3000/blogs/20

###
POST http://localhost:3000/tags
Content-Type: application/json

{
    "tagname":"dogs"
}

###

POST http://localhost:3000/create/comment/3
Content-Type: application/json

{
    "user_id": 7,
    "content": "hmmmmm"
}

###

GET http://localhost:3000/comments

###
PUT http://localhost:3000/update/comment/4
Content-Type: application/json

{
    "post_id": 3,
    "user_id": 7,
    "content": "Im four"
}

###
GET http://localhost:3000/tags

###

GET http://localhost:3000/relation

###

POST http://localhost:3000/relation
Content-Type: application/json

{
    "post_id": 3,
    "tag_id": 1
}

###
DELETE  http://localhost:3000/relation
Content-Type: application/json

{
    "post_id": 3,
    "tag_id": 1
}